### PR TITLE
bug fix for setting breakpoints

### LINKED ISSUE #69: Bug setting breakpoints in JS debugger
setting breakpoints in one file removes breakpoints in other files

### PR DESCRIPTION
**Pull request by zzzwan**
bug fix for setting breakpoints in js debugger

### CODE REVIEW

File: client/JSDebugger/mlDebug.ts [hunk 1]
```diff
@@ -175,24 +175,23 @@ export class MLDebugSession extends LoggingDebugSession {
...
                     column: breakpoint.column,
                     condition: breakpoint.condition
                 })) //construct the set of new breakpoints, better ways?
             })
 
-            const toDelete = new Set([...this._bpCache].filter(x => !newBp.has(x)))
-            const toAdd = new Set([...newBp].filter(x => !this._bpCache.has(x)))
-            this._bpCache = newBp
+            const toDelete = (path in this._bpCache) ? new Set([...this._bpCache[path]].filter(x => !newBp.has(x))) : new Set()
+            const toAdd = (path in this._bpCache) ? new Set([...newBp].filter(x => !this._bpCache[path].has(x))) : newBp
```
Comment (mikrovvelle) [inline client/JSDebugger/mlDebug.ts:188]: This is starting to look pretty complicated. Is there a reason not to just clear all the old breakpoints in ML, and then set the new ones?
